modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
issueTrackerURL="https://github.com/Ephys/mc-random-plant-heights/issues"
[[mods]]
modId="random_plant_heights"
version="${jarVersion}"
displayName="Random Plant Heights"
updateJSONURL="https://mc-curse-update-checker.herokuapp.com/413814"
displayURL="https://github.com/Ephys/mc-random-plant-heights"
#logoFile="examplemod.png"
#credits=""
authors="ephys"
description='''
Makes sugar canes and cacti grow to variable heights based on x-z coordinates

Makes vines stop growing after a given randomised height
'''
[[dependencies.random_plant_heights]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.random_plant_heights]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.16.4]"
    ordering="NONE"
    side="BOTH"
